{
 "title": "SurfLog",
 "time": { "from": "2023-08-18T22:00:00.000Z", "to": "2023-08-29T21:59:59.000Z" },
 "panels": [
  {
   "title": "swellDirection",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  time, dwd, icon, meteo, noaa\nFROM df_swellDirection\nWHERE\n  $__timeFilter(time)\nORDER BY time",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "swellDirection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "swellHeight",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  time, dwd, icon, meteo, noaa\nFROM df_swellHeight\nWHERE\n  $__timeFilter(time)\nORDER BY time",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "swellHeight",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "swellPeriod",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  time, dwd, icon, meteo, noaa\nFROM df_swellPeriod\nWHERE\n  $__timeFilter(time)\nORDER BY time",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "swellPeriod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "waveHeight",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  time, dwd, icon, meteo, noaa\nFROM df_waveHeight\nWHERE\n  $__timeFilter(time)\nORDER BY time",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "waveHeight",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "timeField": "time"
    }
   ]
  }
 ]
}