version: "3.0"

services:

  grafana:
    image: grafana/grafana:8.5.2
    environment:
      GF_SERVER_ROOT_URL: http://192.168.99.100:5000
      GF_LOG_LEVEL: debug
      GF_SERVER_DOMAIN: localhost
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_USERS_DEFAULT_THEME: light
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always

    volumes:
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/plugins:/var/lib/grafana/plugins

    networks:
      - traefik

  db:
    container_name: surflog_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'surflog_db'
      MYSQL_USER: 'surflog_db'
      MYSQL_PASSWORD: 'surflog_db'
      MYSQL_ROOT_PASSWORD: 'surflog_db'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - traefik
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.14.0
    environment:
      xpack.security.enabled: 'false'
      discovery.type: 'single-node'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - traefik
    restart: always
    
networks:
    traefik: