apiVersion: 1

datasources:
    - name: surflog_db
      uid: surflog_db
      type: mysql
      url: db
      database: surflog_db
      user: surflog_db
      editable: true
      secureJsonData:
        password: surflog_db
      jsonData:
        sslmode: "disable"
    - name: surflog_elastic
      type: elasticsearch
      uid: surflog_elastic
      database: "surflog"
      editable: true
      basicAuth: true
      basicAuthUser: admin
      url: localhost:9200
      jsonData:
        tlsSkipVerify: true
        timeField: "time"
        esVersion: 8.0.0
        max_concurrent_shard_requests: 5
      secureJsonData:
        basicAuthPassword: "admin"